<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Sitemap_model extends CI_Model
{
  


    function generate($table)
    {
        $this->db->select('judul_seo,hari,tanggal,jam');
        $this->db->from($table);
        $this->db->order_by('id_berita',"DESC");
        $query = $this->db->get();
        return $query->result();
    }
    
    function generate_projek($table)
    {
        $this->db->select('judul_seo,hari,tanggal,jam');
        $this->db->from($table);
        $this->db->order_by('id_projek',"DESC");
        $query = $this->db->get();
        return $query->result();
    }
    function generate_harga($table)
    {
        $this->db->select('judul_seo,hari,tanggal,jam');
        $this->db->from($table);
        $this->db->order_by('id_harga',"DESC");
        $query = $this->db->get();
        return $query->result();
    }
    
    function generate_bisnis($table)
    {
        $this->db->select('namabisnis_seo,hari,tanggal,jam');
        $this->db->from($table);
        $this->db->order_by('id_bisnis',"DESC");
        $query = $this->db->get();
        return $query->result();
    }
    function generate_kategori($table)
    {
        $this->db->select('kategori_seo');
        $this->db->from($table);
        $this->db->order_by('id_kategori',"DESC");
        $query = $this->db->get();
        return $query->result();
    }

   
}

/* End of file Berita_model.php */
/* Location: ./application/models/Berita_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-10-17 02:19:21 */
/* http://harviacode.com */
